topp_tracker:
  sampling_frequency: 100
  n_gridpoints: 500
  request_permission: False

  constraints:

    velocity:
      x: 5
      y: 5
      z: 10
      yaw: 2.5

    acceleration:
      x: 2.5
      y: 2.5
      z: 10
      yaw: 2.5