topp_tracker:
  sampling_frequency: 500
  n_gridpoints: 500
  request_permission: False

  constraints:

    velocity:
      x: 5
      y: 5
      z: 5
      yaw: 2.5

    acceleration:
      x: 10
      y: 10
      z: 10
      yaw: 1.5